INSERT INTO public.encryption_challenges
(team_role, module, title, story, task_outline, files, file_metadata, command_outputs, hints, tools_whitelist, flag_hash, flag_preview, difficulty, xp_reward)
VALUES
('blue', 'rsa-aes', 'توقيع عقد رقمي',
 'محامي الشركة يحتاج توقيع رقمي على contract.txt باستخدام المفتاح الخاص المرفق. التوقيع يجب أن يكون حقيقياً وقابلاً للتحقق.', 'وقّع contract.txt باستخدام private_key.pem. الـ flag هو hash 256-bit للتوقيع base64.',
 '{"contract.txt": "U0VSVklDRSBBR1JFRU1FTlQKClRoaXMgYWdyZWVtZW50IGlzIGVudGVyZWQgaW50byBvbiAyMDI2LTA0LTE1CmJldHdlZW4gQXBleCBDb3JwIChQcm92aWRlcikgYW5kIFplblRlY2ggR21iSCAoQ2xpZW50KS4KClNjb3BlOiBTZWN1cml0eSBhdWRpdCBvZiBaZW5UZWNoIGluZnJhc3RydWN0dXJlCkR1cmF0aW9uOiA5MCBkYXlzCkZlZTogJDI1MCwwMDAgVVNECgpTaWduZWQ6IF9fX19fX19fX19fX19fX19fX19f", "private_key.pem": "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQW1Fd2dnSmRBZ0VBQW9HQkFOblpqWW1OWkMzUGQzQ2kKazBLTVMvcEU2VUJqdlJNUEhNWjZMNEhuN091ZHVLcGg1d0llN2VnZkI4K1l0T0wyeFlNbWxESk5nMWRjME1MNAo2OTlISTRwcmJsN1pCL0dndlp3WWFSSTYwZXVXUVZnMHBhS2k2TTZMZFVnNlhyVHhJdEM5d2o5Y1BtaGZuOHp2CnhCY1dBSER4eUluT2ROQS83UDJXSEI1OHJScG5BZ01CQUFFQ2dZQmx4RHBaTW9MRTM3RUZIZjA2emoxRDZXTXAKSUM2WU02d1dqOGVYb05kTmJmMXhJcEQrcmFJbm1DOVc3Qmc4R2xsRUhnYUd4UzBBNTZ2aUdOUmZGbVZrREVKLwpjUVAyM3lkMzFBZjFHL2ZURTc3M0tQajRma3lJOWNlYldRcU56WDhBWE5HaXdQOFJRN0NQelJFcEhKK2JNU1FWCloxN2IvOTRjbk1iQWdJNlZRUUpCQVBpdXQwaURsNVd4V0FaeTFGWk9RNS8rQVl3SmdCcnR2YlRRUlJrQ203ckUKWDFzY0cwYStMY1dHeVNmUnlkQkxUcVpNVHZPd0J2Vml1Z1FIemh5UDRpRUNRUURnUXBSY2ZGdlN3SzdGdW1UMQp5bUY3cE1GdXM5cU8xREtLN2xwL245czd3NVRaaDhRRVhFZGpxK1ZqZW5sZjlUenB0eWo5WGp1UlAxeTlyT0lVClIzdUhBa0VBODBHY3djOFBPWHVIbW84Nnk4MjA4c3o1NEd6dXBlakd1QmMrY0ErUUcrcTVTQnMvUnowQzh3UTgKd3JuQkN3S1BSYmJCU0RoNUpoSFQyZHQwcjVYRFlRSkFXOURtalRjZElSeGljZkh1Zy9Ob0ZnZE9hdFNZRndJcAo3MWZIRlptTldOcXFocVZmUzZtOFVNS0FHRXA4aHgwUTQxOXFHTklMOFZ2UHpKaUx0MkhNNFFKQkFOQlA3bW5rCkdmNmRVZ2FlaEVwZ0lkcTV1Qk1WdXJ2UzJlU3prWFkwVFA5akZOcXJjTWxueThjSGlBWWt1L0pOUXBWWUZaNjcKbkJCR1cxU1p2SGs3RkNjPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="}'::jsonb, '{"contract.txt": {"encoding": "utf-8"}, "private_key.pem": {"encoding": "utf-8"}}'::jsonb, '{"cat:contract.txt": {"stdout": "SERVICE AGREEMENT\n\nThis agreement is entered into on 2026-04-15\nbetween Apex Corp (Provider) and ZenTech GmbH (Client).\n\nScope: Security audit of ZenTech infrastructure\nDuration: 90 days\nFee: $250,000 USD\n\nSigned: ____________________", "stderr": "", "exit_code": 0}, "openssl:sign": {"stdout": "HoUdXaZniZ66dmbSUYVisQC2jJ1GIUqU8ahFwqMFB1WAHBqwwpsQZeWXtibr1POY7ZVL6UdCV8mDABco...", "stderr": "", "exit_code": 0}, "ls": {"stdout": "contract.txt\nprivate_key.pem", "stderr": "", "exit_code": 0}}'::jsonb,
 '["راجع صيغة PSS في التواقيع الرقمية", "تأكد من الـ padding: PKCS7 لـ CBC، tag 16-byte لـ GCM"]'::jsonb,
 ARRAY['cat', 'ls', 'echo', 'openssl', 'sha256sum', 'base64', 'file'],
 '3979f25d5ce35d03ccefd8bb98cf891c5eabd90322fe4f76541e52fdde4ebe2e', 'CyberArena{HoUdXaZniZ66dmbSUYVisQC2jJ1GIUqU8ahFwqMFB1WAHBqwwpsQZeWXtibr1POY}',
 'قوي', 200);